### ISSUE TITLE
Add a restart button to the toolbar

### ISSUE THREAD

**Issue by pitag-ha** [SaySayo/vscode-ocaml-notebook#7]
As discussed, let's add a `restart` button to the toolbar just like Jupyter does. The restart button should restart the notebook controller (i.e. notebook kernel). Let me break down this task into 4 smaller tasks:
- [x] As a first step, let's only focus on the visual part of the task: for now, only add a button to the toolbar without "on-click"-implementation. That has to be done in the vscode extension manifest (i.e. `package.json`). For that, ou can more or less copy and paste the following two entries from the Jupyter implementation:
      -  https://github.com/microsoft/vscode-jupyter/blob/main/package.json#L645-L655 (for simplicity, I'd always enable this for now and also, I wouldn't include an icon for now)
      - https://github.com/microsoft/vscode-jupyter/blob/main/package.json#L914-L920 (same thing: I wouldn't bother about the `when` for now )
 - [x] Write a first "on-click" function, which (for now) doesn't restart the kernel, but logs something to the console. For that, you need the [registerTextEditorCommand](https://code.visualstudio.com/api/references/vscode-api#commands.registerTextEditorCommand) function from the VSCode API. So let's break this down into two smaller sub-tasks:
       - [ ] Write a binding for  [registerTextEditorCommand](https://code.visualstudio.com/api/references/vscode-api#commands.registerTextEditorCommand)
       - [ ] Use the `registerTextEditorCommand` to register your printing "on-click"-function (in this context simply called "callback"). Notice that `registerTextEditorCommand` returns a `disposable`, which needs to be passed to `ExtensionContext.subscribe` in the same way the disposable coming from the serializer is passed to it.
 - [x] Improve your "on-click"-function. Now, instead of printing something, we really want to restart the kernel. For that, you can simply initialize `Toploop`
 - [x] (This step can also be done earlier if you want): Have a look at how your button looks like and improve it visually. It might be nicer to make an `svg` as the icon instead of the plain text you have now (I don't know though. You can decide that for yourself :)), which is what both Jupyter and vscode-ocaml-platform do for button icons.

**Comment by SaySayo** [comment]
Resolved with #8
